import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "./_components/navbar/navbar.component";
import AddressProvider from "./providers/address.provider";
import MetamaskProvider from "./providers/metamask.provider";
import "./global.styles.css";
import NftTokensProvider from "./providers/nft-tokens.provider";
import ActionPopup from "./_components/action-popup/action-popup.component";
import PopupProvider from "./providers/popup.provider";
import CustomTokensProvider from "./providers/custom-tokens.provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MetamaskProvider>
          <AddressProvider>
            <NftTokensProvider>
              <CustomTokensProvider>
                <PopupProvider>
                  <Navbar />
                  {children}
                  <ActionPopup />
                </PopupProvider>
              </CustomTokensProvider>
            </NftTokensProvider>
          </AddressProvider>
        </MetamaskProvider>
      </body>
    </html>
  );
}
