import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "./_components/navbar/navbar.component";
import AddressProvider from "./providers/address.provider";
import MetamaskProvider from "./providers/metamask.provider";
import "./global.styles.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MetamaskProvider>
          <AddressProvider>
            <Navbar />
            {children}
          </AddressProvider>
        </MetamaskProvider>
      </body>
    </html>
  );
}
