export const PINATA_KEY = "<YOUR_PINATA_API_KEY>";
export const PINATA_GATEWAY = "<YOUR_PINATA_API_GATEWAY>";

export const DEFAULT_READ_WALLET = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266";
export const REPLICATE_API_TOKEN = "<YOUR_REPLICATE_API_TOKEN>";
